### ISSUE TITLE
好像有已完成的翻译，请求一下转载？

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/nlp-pytorch-zh#1]
<https://yifdu.github.io/2018/12/20/Natural-Language-Processing-with-PyTorch%EF%BC%88%E5%9B%9B%EF%BC%89/>

<https://yifdu.github.io/2018/12/21/Natural-Language-Processing-with-PyTorch%EF%BC%88%E4%BA%94%EF%BC%89/>

<https://yifdu.github.io/2018/12/19/Natural-Language-Processing-with-PyTorch%EF%BC%88%E4%B8%89%EF%BC%89/>

<https://yifdu.github.io/2019/06/12/%E8%8F%9C%E9%B8%9F%E5%AD%A6NLP%EF%BC%88%E4%B9%9D%EF%BC%89/>

**Comment by jiangzhonglian** [comment]
我发邮件申请一下授权

**Comment by jiangzhonglian** [comment]
![image](https://user-images.githubusercontent.com/9199175/61036668-1d4a3780-a3fc-11e9-8994-df911c841559.png)
