### ISSUE TITLE
pdf,mobi文件已编译，并放到阿里云服务器，已开启CDN加速。

### ISSUE THREAD

**Issue by Tlntin** [apachecn/nlp-pytorch-zh#30]
国内在线阅读：https://book.ztjs.top/nlp_pytorch/
pdf下载：https://book.ztjs.top/nlp_pytorch/nlp-pytorch-zh.pdf
epub下载：https://book.ztjs.top/nlp_pytorch/nlp-pytorch-zh.epub
mobi下载：https://book.ztjs.top/nlp_pytorch/nlp-pytorch-zh.mobi

**Comment by jiangzhonglian** [comment]
谢谢，我会补充到首页的

**Comment by jiangzhonglian** [comment]
你的网址是不是挂掉呢？

**Comment by Tlntin** [comment]
已经弄好了，mobi文件忘记保存了，正在重新编译。

**Comment by jiangzhonglian** [comment]
好的好的，辛苦小哥哥，我呆会就更新项目

**Comment by Tlntin** [comment]
恩恩。没事

**Comment by jiangzhonglian** [comment]
需要我给你的网址备注什么吗？ 小哥哥
